### ISSUE TITLE
Request Fails with "error requesting upstream status"

### ISSUE THREAD

**Issue by BUR4KBEY** [vbrandl/sablier-proxy#39]
# MongoDB Integration with Sablier Proxy - Request Fails with "error requesting upstream status"

## Issue Description
I'm trying to set up Sablier Proxy with a MongoDB database to automatically stop the database when there are no active connections. However, I'm encountering an "error requesting upstream status" when attempting to connect via MongoDB Compass.

## Setup Details

**Project Build Command:**
I built the project from source using:
```
docker buildx build -t sablier-proxy .
```

**Docker Compose Configuration:**
```yaml
services:
  proxy:
    image: sablier-proxy
    container_name: mongo-proxy
    ports:
      - 8080:8080
    environment:
      LISTEN: '0.0.0.0:8080'
      UPSTREAM: 'mongodb:27017'
      NAMES: 'mongo'
      GROUP: 'demo'
      SESSION_DURATION: '1m'
      BLOCKING_TIMEOUT: '15s'
    networks:
      shared:
      proxy:
    restart: unless-stopped
  mongodb:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db
    networks:
      shared:
    restart: unless-stopped

networks:
  shared:
    driver: bridge
  proxy:
    external: true
```

The `sablier` container is inside the `proxy` network, allowing `mongo-proxy` to access both `mongo` and `sablier` containers without networking issues.

## Error
When running `docker compose up -d && docker compose logs proxy -f` and attempting to connect via MongoDB Compass with `mongodb://localhost:8080`, I consistently get the error: `error requesting upstream status`.

## Root Cause Identified
After investigation, I found a critical difference between the official Traefik plugin implementation and this project:

1. **Official Traefik Plugin Implementation:** Uses the format `?foo=bar&names=name1&names=name2` for repeated query parameters
2. **Current Project Implementation:** Uses `?foo=bar&names=["name1","name2"]` format

The official Traefik implementation uses repeated parameters:
```go
for _, name := range c.splittedNames {
    q.Add("names", name)
}
```
[Source](https://github.com/sablierapp/sablier/blob/cc23853966a1f92578ace0284f654fbf1ba2e746/plugins/traefik/config.go#L157-L159)

This query parameter formatting mismatch appears to be causing the request failures.

## Solution

I'm going to create a PR to solve this issue.
